package ExceptionHandling;

import java.util.Scanner;

public class ExceptionHandligBlock {

	public static void main(String[] args) {

		int a,b;
		
		Scanner s = new Scanner(System.in);
		System.out.println("Enter First Number");
		a=s.nextInt();
		System.out.println("Enter Second Number");
		b=s.nextInt();
		
		try {
			int c = a/b; // 10/0 ArithmeticException
			
			int[] a= {
					10.
					20,
					30
			};
		} catch(ArithmeticException e) {
			System.out.println("Inside Arithmatic Expresion ");
			System.out.println(e.getMessage()); // show message only not show on class
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("Inside Array Indec out of Bounds");
			System.out.println(e.getMessage());
		}
	}

}
